[font]
size = 16

[font.bold]
family = "Caskaydia Cove Nerd Font"
style = "Bold Italic"

[font.bold_italic]
family = "Caskaydia Cove Nerd Font Mono"
style = "SemiBold italic"

[font.italic]
family = "Caskaydia Cove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
